### ISSUE TITLE
CORS error on Firefox

### ISSUE THREAD

**Issue by EmSixTeen** [farnots/RedditToMarkdown#3]
Doesn't work on Firefox for me. Throws a CORS error in console.

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at <postURL>.json. (Reason: CORS request did not succeed). Status code: (null).

**Comment by SagXD** [comment]
Same here too. Using Librewolf

**Comment by TAbdiukov** [comment]
Same on both Chrome and Firefox

**Comment by farnots** [comment]
I made an update in latest commit https://github.com/farnots/RedditToMarkdown/commit/f9fc0be83e99486740cee9745ae2999f798d676c, this should fix the issue

**Comment by pac-71** [comment]
Thanks for the update. It is still broken for me in Edge, Chrome and Opera. It was and still is working on Firefox via direct for me. It was broken in Brave for me previously but now is working. Firefox and Brave are only working direct.

All on the same computer (Windows 11 64-bit 24H2 Build 26100.4946) and network (wifi via range extender). Minimal plugins installed in opera, none in chrome or brave (edge is my main browser). 

Specific URL [https://www.reddit.com/r/ObsidianMD/comments/1n27u16/share_your_dataviewbases_light_bulbah_ha_moments/](https://www.reddit.com/r/ObsidianMD/comments/1n27u16/share_your_dataviewbases_light_bulbah_ha_moments/)

Firefox is up to date Firefox 142.0.1
Brave is up to date Brave 1.81.137 (Official Build) (64-bit) Chromium: 139.0.7258.15

Microsoft Edge Microsoft Edge is up to date. Version 139.0.3405.125 (Official build) (64-bit)
Google Chrome Chrome is up to date Version 139.0.7258.155 (Official Build) (64-bit)
Opera One(version: 121.0.5600.38) Opera is up to date Update stream:Stable Chromium version:137.0.7151.122

**Comment by TAbdiukov** [comment]
It appears to work ok now, @pac-71  do you still experience this issue?
